### ISSUE TITLE
Teacher registration serverless function

### ISSUE THREAD

**Issue by tmaxmax** [FiveIT/eseuri#15]
- [ ] Called manually by us, in order to accept or reject a role request
- [ ] Registers the user as a teacher in the database

**Comment by mateitudose** [comment]
Pai am zis ca asta o facem manual in Hasura...

**Comment by tmaxmax** [comment]
Nu e mult de implementat și oricum la un moment dat va exista si un admin dashboard pentru noi, care va folosi funcția asta.

**Comment by mateitudose** [comment]
Nu e necesar pentru prezentare

**Comment by tmaxmax** [comment]
Postponed.
